env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
plugins:
  - security
extends:
  - airbnb-base
  - plugin:security/recommended
parserOptions:
  ecmaVersion: 12
rules: {
  indent: 2
}
