name: cd-pipeline

# Controls when the action will run. 
on:
  release:
    types:
      - created

  # Allows to run this workflow manually
  workflow_dispatch:

jobs:
  unittests:
    name: run node unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Get package.json nodejs version
      - run: |
          echo "APPLICATION_VERSION=$(cat package.json | jq .version | sed 's/"//g')" >> $GITHUB_ENV
      
      # Building docker image
      # https://github.com/google-github-actions/deploy-cloudrun
      - run: |


        