name: cd-pipeline

# Controls when the action will run. 
on:
  release:
    types:
      - published

  # Allows to run this workflow manually
  workflow_dispatch:

jobs:
  deploy_on_cloud_run:
    name: Deploy app on Google Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Building docker image
      - name: Push to dockerhub regitry
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: andrelramos/vuttr
          tag_with_ref: true

      # Deploy on cloud run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.5.0
        with:
          service: vuttr
          image: andrelramos/vuttr
          credentials: ${{ secrets.GCP_SA_KEY }}


        