name: cd-pipeline

# Controls when the action will run. 
on:
  push:
    tags:
      - v*

  # Allows to run this workflow manually
  workflow_dispatch:

jobs:
  deploy_on_cloud_run:
    name: Deploy app on Google Cloud Run
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: gcr.io/vuttr-bossabox-314921/vuttr
    steps:
      - uses: actions/checkout@v2
      
      # Get package.json nodejs version
      - run: |
          echo "TAG=${{ env.REGISTRY_URL }}:$(cat package.json | jq .engines.node | sed 's/"//g')" >> $GITHUB_ENV

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }} 

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          docker build -t ${{ env.TAG }}

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push ${{ env.TAG }}
          docker tag ${{ env.TAG }} ${{ env.REGISTRY_URL }}:latest
          docker push ${{ env.REGISTRY_URL }}:latest

      # Deploy on cloud run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.5.0
        with:
          service: vuttr
          image: ${{ env.TAG }}
          credentials: ${{ secrets.GCP_SA_KEY }}


        