name: ci-pipeline

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - master

  # Allows to run this workflow manually
  workflow_dispatch:

jobs:
  unittests:
    name: run node unit tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.6
        options: >-
          --tmpfs /data/db
        ports: 
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      
      # Get package.json nodejs version
      - run: |
          echo "NODE_VERSION=$(cat package.json | jq .engines.node | sed 's/"//g')" >> $GITHUB_ENV
          echo "APPLICATION_VERSION=$(cat package.json | jq .version | sed 's/"//g')" >> $GITHUB_ENV

      # Installing nodejs
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      # Installing dependencies
      - run: npm ci

      # Running linter
      - run: npm run lint

      # Running tests
      - run: npm test

      # Creating release
      - if: github.ref == 'refs/heads/master'
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.APPLICATION_VERSION }}
          release_name: Release ${{ env.APPLICATION_VERSION }}
          draft: false
          prerelease: false